// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdL1pq4HIWRgEjuh6uYrd5EYeHVQMEMGg',
    appId: '1:781743853982:web:4872fa6b88488fd828c68f',
    messagingSenderId: '781743853982',
    projectId: 'aplikasi-order-makanan',
    authDomain: 'aplikasi-order-makanan.firebaseapp.com',
    storageBucket: 'aplikasi-order-makanan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4UNdQ1gGDCAqWCsP3CtCS7oFlsL0Fqs',
    appId: '1:781743853982:android:767d86c6e120cb6e28c68f',
    messagingSenderId: '781743853982',
    projectId: 'aplikasi-order-makanan',
    storageBucket: 'aplikasi-order-makanan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Gzm24fIvAsg7HNKUBVk2l1m5NaSpjec',
    appId: '1:781743853982:ios:a5de3efeb8830a6228c68f',
    messagingSenderId: '781743853982',
    projectId: 'aplikasi-order-makanan',
    storageBucket: 'aplikasi-order-makanan.appspot.com',
    iosBundleId: 'com.example.order2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Gzm24fIvAsg7HNKUBVk2l1m5NaSpjec',
    appId: '1:781743853982:ios:a5de3efeb8830a6228c68f',
    messagingSenderId: '781743853982',
    projectId: 'aplikasi-order-makanan',
    storageBucket: 'aplikasi-order-makanan.appspot.com',
    iosBundleId: 'com.example.order2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdL1pq4HIWRgEjuh6uYrd5EYeHVQMEMGg',
    appId: '1:781743853982:web:0c15f3867239c4b728c68f',
    messagingSenderId: '781743853982',
    projectId: 'aplikasi-order-makanan',
    authDomain: 'aplikasi-order-makanan.firebaseapp.com',
    storageBucket: 'aplikasi-order-makanan.appspot.com',
  );
}
